/// Static cross-brand paint equivalence map.
/// Key format: 'brand:code'  →  list of (brand, code) equivalents.
/// Sources: community equivalence tables + modellistipontassieve.com (approximate).
const Map<String, List<(String, String)>> kPaintEquivalences = {
  // ── Vallejo Model Color ────────────────────────────────────────────────────
  'vallejo:70.950': [('citadel', 'Abaddon Black'), ('tamiya', 'XF-1')],
  'vallejo:70.951': [('citadel', 'Corax White'), ('tamiya', 'XF-2')],
  'vallejo:70.947': [('citadel', 'Mephiston Red'), ('tamiya', 'XF-7')],
  'vallejo:70.963': [('citadel', 'Macragge Blue'), ('tamiya', 'XF-8')],
  'vallejo:70.880': [('citadel', 'Death World Forest'), ('tamiya', 'XF-58')],
  'vallejo:70.976': [('citadel', 'Castellan Green'), ('tamiya', 'XF-65')],
  'vallejo:70.916': [('citadel', 'Zandri Dust'), ('tamiya', 'XF-57')],
  'vallejo:70.875': [('citadel', 'Rakarth Flesh'), ('tamiya', 'XF-15')],
  'vallejo:70.918': [('citadel', 'Leadbelcher'), ('tamiya', 'XF-56')],
  'vallejo:70.997': [('citadel', 'Balthasar Gold'), ('tamiya', 'XF-6')],
  'vallejo:70.981': [('citadel', 'Averland Sunset'), ('tamiya', 'XF-3')],
  'vallejo:70.957': [('citadel', 'Bugman\'s Glow')],
  'vallejo:70.965': [('citadel', 'Incubi Darkness'), ('tamiya', 'XF-27')],
  'vallejo:70.900': [('citadel', 'Rhinox Hide'), ('tamiya', 'XF-10')],

  // ── Citadel → Vallejo reverse ─────────────────────────────────────────────
  'citadel:Abaddon Black': [('vallejo', '70.950'), ('tamiya', 'XF-1')],
  'citadel:Corax White':   [('vallejo', '70.951'), ('tamiya', 'XF-2')],
  'citadel:Mephiston Red': [('vallejo', '70.947'), ('tamiya', 'XF-7')],
  'citadel:Macragge Blue': [('vallejo', '70.963'), ('tamiya', 'XF-8')],
  'citadel:Leadbelcher':   [('vallejo', '70.918'), ('tamiya', 'XF-56')],
  'citadel:Balthasar Gold':    [('vallejo', '70.997'), ('tamiya', 'XF-6')],
  'citadel:Averland Sunset':   [('vallejo', '70.981'), ('tamiya', 'XF-3')],
  'citadel:Zandri Dust':       [('vallejo', '70.916'), ('tamiya', 'XF-57')],
  'citadel:Death World Forest':[('vallejo', '70.880'), ('tamiya', 'XF-58')],
  'citadel:Castellan Green':   [('vallejo', '70.976'), ('tamiya', 'XF-65')],

  // ── Tamiya XF (opaco/metallizzato) ───────────────────────────────────────
  'tamiya:XF-1':  [('vallejo', '70.950'), ('citadel', 'Abaddon Black'), ('humbrol', '33'),  ('gunze', 'H74')],
  'tamiya:XF-2':  [('vallejo', '70.951'), ('citadel', 'Corax White'),   ('humbrol', '34'),  ('gunze', 'H11')],
  'tamiya:XF-3':  [('vallejo', '70.981'), ('citadel', 'Averland Sunset'), ('humbrol', '99')],
  'tamiya:XF-4':  [('humbrol', '81')],
  'tamiya:XF-5':  [('humbrol', '101'), ('gunze', 'H340')],
  'tamiya:XF-6':  [('vallejo', '70.997'), ('citadel', 'Balthasar Gold'), ('humbrol', '12'), ('gunze', 'H10')],
  'tamiya:XF-7':  [('vallejo', '70.947'), ('citadel', 'Mephiston Red'),  ('humbrol', '60'), ('gunze', 'H13'), ('gunze', 'H23'), ('gunze', 'H327')],
  'tamiya:XF-8':  [('vallejo', '70.963'), ('citadel', 'Macragge Blue'),  ('humbrol', '25'), ('gunze', 'H35')],
  'tamiya:XF-9':  [('humbrol', '73'),  ('gunze', 'H13')],
  'tamiya:XF-10': [('vallejo', '70.900'), ('humbrol', '98')],
  'tamiya:XF-11': [('humbrol', '75'),  ('gunze', 'H36')],
  'tamiya:XF-12': [('humbrol', '64'),  ('gunze', 'H51')],
  'tamiya:XF-13': [('humbrol', '116'), ('gunze', 'H309'), ('gunze', 'H60')],
  'tamiya:XF-14': [('humbrol', '147'), ('gunze', 'H57')],
  'tamiya:XF-15': [('vallejo', '70.875'), ('humbrol', '61'), ('gunze', 'H44')],
  'tamiya:XF-16': [('humbrol', '56'),  ('gunze', 'H8')],
  'tamiya:XF-17': [('humbrol', '104')],
  'tamiya:XF-18': [('humbrol', '96')],
  'tamiya:XF-19': [('humbrol', '64'),  ('gunze', 'H334')],
  'tamiya:XF-20': [('humbrol', '126'), ('gunze', 'H306')],
  'tamiya:XF-21': [('humbrol', '90'),  ('gunze', 'H31')],
  'tamiya:XF-22': [('humbrol', '92')],
  'tamiya:XF-23': [('humbrol', '65'),  ('gunze', 'H67')],
  'tamiya:XF-24': [('humbrol', '123')],
  'tamiya:XF-25': [('humbrol', '87')],
  'tamiya:XF-26': [('humbrol', '30'),  ('gunze', 'H320')],
  'tamiya:XF-27': [('vallejo', '70.965'), ('humbrol', '91')],
  'tamiya:XF-49': [('humbrol', '72'), ('humbrol', '26')],
  'tamiya:XF-50': [('humbrol', '96')],
  'tamiya:XF-51': [('humbrol', '155')],
  'tamiya:XF-52': [('humbrol', '29'),  ('gunze', 'H72')],
  'tamiya:XF-53': [('humbrol', '153'), ('gunze', 'H53')],
  'tamiya:XF-54': [('humbrol', '140'), ('gunze', 'H317')],
  'tamiya:XF-55': [('humbrol', '28'),  ('gunze', 'H311')],
  'tamiya:XF-56': [('vallejo', '70.918'), ('citadel', 'Leadbelcher'), ('humbrol', '56')],
  'tamiya:XF-57': [('vallejo', '70.916'), ('citadel', 'Zandri Dust'), ('humbrol', '83')],
  'tamiya:XF-58': [('vallejo', '70.880'), ('citadel', 'Death World Forest'), ('humbrol', '30'), ('gunze', 'H73')],
  'tamiya:XF-59': [('humbrol', '93'),  ('gunze', 'H79')],
  'tamiya:XF-60': [('humbrol', '84')],
  'tamiya:XF-61': [('humbrol', '30'),  ('gunze', 'H320')],
  'tamiya:XF-62': [('humbrol', '66'),  ('gunze', 'H78')],
  'tamiya:XF-63': [('humbrol', '67'),  ('gunze', 'H32')],
  'tamiya:XF-64': [('humbrol', '160')],
  'tamiya:XF-65': [('vallejo', '70.976'), ('citadel', 'Castellan Green'), ('humbrol', '116'), ('gunze', 'H309')],
  'tamiya:XF-66': [('humbrol', '87'), ('humbrol', '62')],

  // ── Tamiya X (lucido/metallizzato) ───────────────────────────────────────
  'tamiya:X-1':  [('humbrol', '21'),  ('gunze', 'H2')],
  'tamiya:X-2':  [('humbrol', '22'),  ('gunze', 'H1')],
  'tamiya:X-3':  [('humbrol', '15'),  ('gunze', 'H5')],
  'tamiya:X-4':  [('humbrol', '14'),  ('gunze', 'H15')],
  'tamiya:X-5':  [('humbrol', '3'),   ('gunze', 'H6')],
  'tamiya:X-6':  [('humbrol', '18'),  ('gunze', 'H14')],
  'tamiya:X-7':  [('humbrol', '19'),  ('gunze', 'H3')],
  'tamiya:X-8':  [('humbrol', '69'),  ('gunze', 'H4')],
  'tamiya:X-9':  [('humbrol', '10'),  ('gunze', 'H7')],
  'tamiya:X-10': [('humbrol', '53'),  ('gunze', 'H76')],
  'tamiya:X-11': [('humbrol', '11'),  ('gunze', 'H8')],
  'tamiya:X-12': [('humbrol', '16'),  ('gunze', 'H9')],
  'tamiya:X-13': [('humbrol', '52'),  ('gunze', 'H88')],
  'tamiya:X-14': [('humbrol', '48'),  ('gunze', 'H20')],
  'tamiya:X-15': [('humbrol', '38'),  ('gunze', 'H16')],
  'tamiya:X-16': [('humbrol', '68'),  ('gunze', 'H39')],
  'tamiya:X-17': [('humbrol', '200'), ('gunze', 'H19')],
  'tamiya:X-18': [('humbrol', '85'),  ('gunze', 'H77')],
  'tamiya:X-22': [('humbrol', '35'),  ('gunze', 'H30')],
  'tamiya:X-23': [('gunze', 'H93')],
  'tamiya:X-24': [('gunze', 'H91')],
  'tamiya:X-25': [('gunze', 'H94')],
  'tamiya:X-26': [('gunze', 'H92')],
  'tamiya:X-27': [('gunze', 'H90')],

  // ── Humbrol → Tamiya ──────────────────────────────────────────────────────
  // (dove un Humbrol corrisponde a più Tamiya si elencano tutti)
  'humbrol:3':   [('tamiya', 'X-5')],
  'humbrol:10':  [('tamiya', 'X-9')],
  'humbrol:11':  [('tamiya', 'X-11')],
  'humbrol:12':  [('tamiya', 'XF-6')],
  'humbrol:14':  [('tamiya', 'X-4')],
  'humbrol:15':  [('tamiya', 'X-3')],
  'humbrol:16':  [('tamiya', 'X-12')],
  'humbrol:18':  [('tamiya', 'X-6')],
  'humbrol:19':  [('tamiya', 'X-7')],
  'humbrol:21':  [('tamiya', 'X-1')],
  'humbrol:22':  [('tamiya', 'X-2')],
  'humbrol:25':  [('tamiya', 'XF-8')],
  'humbrol:28':  [('tamiya', 'XF-55')],
  'humbrol:29':  [('tamiya', 'XF-52')],
  'humbrol:30':  [('tamiya', 'XF-26'), ('tamiya', 'XF-58'), ('tamiya', 'XF-61')],
  'humbrol:33':  [('tamiya', 'XF-1')],
  'humbrol:34':  [('tamiya', 'XF-2')],
  'humbrol:35':  [('tamiya', 'X-22')],
  'humbrol:38':  [('tamiya', 'X-15')],
  'humbrol:48':  [('tamiya', 'X-14')],
  'humbrol:52':  [('tamiya', 'X-13')],
  'humbrol:53':  [('tamiya', 'X-10')],
  'humbrol:56':  [('tamiya', 'XF-16'), ('tamiya', 'XF-56')],
  'humbrol:60':  [('tamiya', 'XF-7')],
  'humbrol:61':  [('tamiya', 'XF-15')],
  'humbrol:64':  [('tamiya', 'XF-12'), ('tamiya', 'XF-19')],
  'humbrol:65':  [('tamiya', 'XF-23')],
  'humbrol:66':  [('tamiya', 'XF-62')],
  'humbrol:67':  [('tamiya', 'XF-63')],
  'humbrol:68':  [('tamiya', 'X-16')],
  'humbrol:69':  [('tamiya', 'X-8')],
  'humbrol:72':  [('tamiya', 'XF-49')],
  'humbrol:73':  [('tamiya', 'XF-9')],
  'humbrol:75':  [('tamiya', 'XF-11')],
  'humbrol:81':  [('tamiya', 'XF-4')],
  'humbrol:83':  [('tamiya', 'XF-57')],
  'humbrol:84':  [('tamiya', 'XF-60')],
  'humbrol:85':  [('tamiya', 'X-18'), ('gunze', 'H77')],
  'humbrol:24':  [('gunze', 'H34')],
  'humbrol:94':  [('gunze', 'H71')],
  'humbrol:87':  [('tamiya', 'XF-25'), ('tamiya', 'XF-66')],
  'humbrol:90':  [('tamiya', 'XF-21')],
  'humbrol:91':  [('tamiya', 'XF-27')],
  'humbrol:92':  [('tamiya', 'XF-22')],
  'humbrol:93':  [('tamiya', 'XF-59')],
  'humbrol:96':  [('tamiya', 'XF-18'), ('tamiya', 'XF-50')],
  'humbrol:98':  [('tamiya', 'XF-10')],
  'humbrol:99':  [('tamiya', 'XF-3')],
  'humbrol:101': [('tamiya', 'XF-5')],
  'humbrol:104': [('tamiya', 'XF-17')],
  'humbrol:116': [('tamiya', 'XF-13'), ('tamiya', 'XF-65')],
  'humbrol:123': [('tamiya', 'XF-24')],
  'humbrol:126': [('tamiya', 'XF-20')],
  'humbrol:140': [('tamiya', 'XF-54')],
  'humbrol:147': [('tamiya', 'XF-14')],
  'humbrol:153': [('tamiya', 'XF-53')],
  'humbrol:155': [('tamiya', 'XF-51')],
  'humbrol:160': [('tamiya', 'XF-64')],
  'humbrol:26':  [('tamiya', 'XF-49')],
  'humbrol:62':  [('tamiya', 'XF-66')],
  'humbrol:105': [('gunze', 'H340')],
  'humbrol:128': [('gunze', 'H53'), ('gunze', 'H307')],
  'humbrol:195': [('tamiya', 'XF-13'), ('gunze', 'H60')],
  'humbrol:200': [('tamiya', 'X-17')],

  // ── Gunze Aqueous H-series → Tamiya ──────────────────────────────────────
  'gunze:H1':   [('tamiya', 'X-2')],
  'gunze:H2':   [('tamiya', 'X-1')],
  'gunze:H3':   [('tamiya', 'X-7')],
  'gunze:H4':   [('tamiya', 'X-8')],
  'gunze:H5':   [('tamiya', 'X-3')],
  'gunze:H6':   [('tamiya', 'X-5')],
  'gunze:H7':   [('tamiya', 'X-9')],
  'gunze:H8':   [('tamiya', 'X-11'), ('tamiya', 'XF-16')],
  'gunze:H9':   [('tamiya', 'X-12')],
  'gunze:H10':  [('tamiya', 'XF-6')],
  'gunze:H11':  [('tamiya', 'XF-2')],
  'gunze:H13':  [('tamiya', 'XF-9'), ('tamiya', 'XF-7')],
  'gunze:H14':  [('tamiya', 'X-6')],
  'gunze:H15':  [('tamiya', 'X-4')],
  'gunze:H16':  [('tamiya', 'X-15')],
  'gunze:H19':  [('tamiya', 'X-17')],
  'gunze:H20':  [('tamiya', 'X-14')],
  'gunze:H30':  [('tamiya', 'X-22')],
  'gunze:H31':  [('tamiya', 'XF-21')],
  'gunze:H32':  [('tamiya', 'XF-63')],
  'gunze:H36':  [('tamiya', 'XF-11')],
  'gunze:H39':  [('tamiya', 'X-16')],
  'gunze:H44':  [('tamiya', 'XF-15')],
  'gunze:H53':  [('tamiya', 'XF-53')],
  'gunze:H57':  [('tamiya', 'XF-14')],
  'gunze:H67':  [('tamiya', 'XF-23')],
  'gunze:H72':  [('tamiya', 'XF-52')],
  'gunze:H73':  [('tamiya', 'XF-58')],
  'gunze:H74':  [('tamiya', 'XF-1')],
  'gunze:H76':  [('tamiya', 'X-10')],
  'gunze:H78':  [('tamiya', 'XF-62')],
  'gunze:H79':  [('tamiya', 'XF-59')],
  'gunze:H88':  [('tamiya', 'X-13')],
  'gunze:H90':  [('tamiya', 'X-27')],
  'gunze:H91':  [('tamiya', 'X-24')],
  'gunze:H92':  [('tamiya', 'X-26')],
  'gunze:H93':  [('tamiya', 'X-23')],
  'gunze:H94':  [('tamiya', 'X-25')],
  'gunze:H306': [('tamiya', 'XF-20')],
  'gunze:H309': [('tamiya', 'XF-13'), ('tamiya', 'XF-65')],
  'gunze:H311': [('tamiya', 'XF-55')],
  'gunze:H317': [('tamiya', 'XF-54')],
  'gunze:H320': [('tamiya', 'XF-26'), ('tamiya', 'XF-61')],
  'gunze:H327': [('tamiya', 'XF-7')],
  'gunze:H334': [('tamiya', 'XF-19')],
  'gunze:H340': [('tamiya', 'XF-5')],
  'gunze:H77':  [('tamiya', 'X-18'), ('humbrol', '85')],
  'gunze:H23':  [('tamiya', 'XF-7')],
  'gunze:H34':  [('humbrol', '24')],
  'gunze:H35':  [('tamiya', 'XF-8')],
  'gunze:H51':  [('tamiya', 'XF-12')],
  'gunze:H60':  [('tamiya', 'XF-13'), ('humbrol', '195')],
  'gunze:H71':  [('humbrol', '94')],
  'gunze:H307': [('humbrol', '128')],
};
